site_name: Molequul
elements: [ hygdrogen, oxygen ]
elements2:
    - name: hydrogen
      number: 1
    - name: helium
      number: 2



items:
    - part_no:   A4786
      descrip:   Water Bucket (Filled)
      price:     1.47
      quantity:  4
    - part_no:   E1628
      descrip:   High Heeled "Ruby" Slippers
      price:     100.27
      quantity:  1